# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Noxie/Desktop/clp-tp-final/Fuentes/Arty-Z7-10-Master.xdc

# IP: ip/ila/ila.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila || ORIG_REF_NAME==ila} -quiet] -quiet

# IP: ip/vio/vio.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio || ORIG_REF_NAME==vio} -quiet] -quiet

# XDC: ip/ila/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila || ORIG_REF_NAME==ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/ila/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila || ORIG_REF_NAME==ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/ila/ila_ooc.xdc

# XDC: ip/vio/vio.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio || ORIG_REF_NAME==vio} -quiet] -quiet
